version: "3"

services:

  spark-master:
    image: spark:3.5.3
    container_name: spark-master
    hostname: spark-master
    working_dir: /opt/app
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /dev/null
      "
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ..:/opt/app
      - ../spark-events:/opt/app/spark-events
      - ../spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  spark-workers:
    image: spark:3.5.3
    # container_name: spark-worker-2
    depends_on:
      - spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
      "
    environment:
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_CORES=3
    ports:
      - "8081-8085:8081"
    volumes:
      - ..:/opt/app
      - ../spark-events:/opt/app/spark-events
      - ../spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    deploy:
      replicas: 3
    
  spark-history:
    image: spark:3.5.3
    container_name: spark-history
    command: >
      bash -c "
      /opt/spark/sbin/start-history-server.sh \
      --properties-file /opt/spark/conf/spark-defaults.conf &&
      tail -f /dev/null
      "
    ports:
      - "18081:18080"
    volumes:
      - ../spark-events:/opt/app/spark-events
      - ../spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    
  jupyter:
    image: spark:3.5.3
    container_name: spark-jupyter
    working_dir: /opt/app/
    depends_on:
      - spark-master
    ports:
      - "8889:8888"
      - "4040-4045:4040-4045"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
    command: >
      bash -c "
      pip install --no-cache-dir jupyter &&
      export PYTHONPATH=/opt/spark/python:$(ls /opt/spark/python/lib/py4j-*.zip) &&
      jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
      "
    volumes:
      - ..:/opt/app
      - ../spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    user: root